### ISSUE TITLE
Incompatible with Flask-Login==0.4.0

### ISSUE THREAD

**Issue by daniel86** [knowrob/docker#136]

**Comment by daniel86** [comment]
@mh0rst  do you know how to fix this with Flask-Login 0.4.0 ?

**Comment by mh0rst** [comment]
I can look into it these days.

**Comment by daniel86** [comment]
I just saw something about auth tokens, that's why I initially referenced you.
But then I realized that it is something flask internal.
It often happens that flask modules, installed via pip, are incompatible with each other,
Hard to maintain, see https://github.com/knowrob/docker/blob/master/flask/Dockerfile#L14

**Comment by mh0rst** [comment]
The module flask-user seems to be responsible for this: https://github.com/lingthio/Flask-User/issues/141
When this issue is fixed, pinning the flask-user version to the fixed version should fix the issue (and removes the need for further version pinning).

**Comment by daniel86** [comment]
still... pinning different versions of flask modules is a maintenance hell.

Same holds for ubuntu packages in docker images (where you can't even force specific versions
without adding special package sources). Since docker caches `apt-get update` I often don't even realize that some update in apt-get or pip package manager breaks openEASE code :/
But flask is definitely the most frequent cause of breaking the code.
